### PR TITLE
feature: enable to set android min api

### PR DESCRIPTION
**Pull request by piiertho**
Add androidMinApi parameter to gradle plugin to enable specify --min-api argument of d8 tool

### CODE REVIEW

**Comment by CedNaru** [comment]
Maybe we can also add the multidex in this PR as well as it's a closely related matter.

**Comment by piiertho** [comment]
> Maybe we can also add the multidex in this PR as well as it's a closely related matter.

Multidex is a legacy feature for Dalvik.
On art it is enabled by default. (So after Android 21)
https://developer.android.com/studio/build/multidex

**Review by CedNaru — APPROVED** [review]

**Comment by chippmann** [comment]
> > Maybe we can also add the multidex in this PR as well as it's a closely related matter.
> 
> Multidex is a legacy feature for Dalvik. On art it is enabled by default. (So after Android 21) https://developer.android.com/studio/build/multidex

Still we need to handle that. AFAIK the d8 tool will generate multiple dex files. Currently we then only add the main dex file to the exported game together with the bootstrap dex file.
But not the other dex files.
But i suggest doing this in a separate PR.

**Review by chippmann — DISMISSED** [review]

**Comment by piiertho** [comment]
> > > Maybe we can also add the multidex in this PR as well as it's a closely related matter.
> > 
> > 
> > Multidex is a legacy feature for Dalvik. On art it is enabled by default. (So after Android 21) https://developer.android.com/studio/build/multidex
> 
> Still we need to handle that. AFAIK the d8 tool will generate multiple dex files. Currently we then only add the main dex file to the exported game together with the bootstrap dex file. But not the other dex files. But i suggest doing this in a separate PR.

I dont think so.
We generate dex files that will be zipped into one jar.  
We should not confuse dex files and jar zipping them.

**Review by chippmann — APPROVED** [review]

**Review by CedNaru — APPROVED** [review]

**Pull request merged**
