### PR TITLE
Feature/update to godot 3.4.2

### PR DESCRIPTION
**Pull request by piiertho**
This updates module to 3.4.2 version of godot.

### CODE REVIEW

**Review by chippmann — CHANGES_REQUESTED** [review]
One thing we forgot to update each time and needs correcting: here the version is still wrong: https://godot-kotl.in/en/stable/contribution/setup/

Just as a note: remember to move the stable tag so the website get's updated. :-)

**Comment by piiertho** [comment]
> One thing we forgot to update each time and needs correcting: here the version is still wrong: https://godot-kotl.in/en/stable/contribution/setup/
> 
> 
> 
> Just as a note: remember to move the stable tag so the website get's updated. :-)

IIRC CI updates stable tag when releasing

**Comment by chippmann** [comment]
> > One thing we forgot to update each time and needs correcting: here the version is still wrong: https://godot-kotl.in/en/stable/contribution/setup/
> > Just as a note: remember to move the stable tag so the website get's updated. :-)
> 
> IIRC CI updates stable tag when releasing

Yeah it should but IIRC it does not work reliably. Didn't we have some problems with it in the past? When i look at our current documentation website, it doesn't seem up to date to me? For example see the version here: https://godot-kotl.in/en/stable/user-guide/versioning/

**Comment by piiertho** [comment]
> > > One thing we forgot to update each time and needs correcting: here the version is still wrong: https://godot-kotl.in/en/stable/contribution/setup/
> 
> > > Just as a note: remember to move the stable tag so the website get's updated. :-)
> 
> > 
> 
> > IIRC CI updates stable tag when releasing
> 
> 
> 
> Yeah it should but IIRC it does not work reliably. Didn't we have some problems with it in the past? When i look at our current documentation website, it doesn't seem up to date to me? For example see the version here: https://godot-kotl.in/en/stable/user-guide/versioning/

True, did not catch this. But stable tag is up to date :/

**Comment by chippmann** [comment]
> > > > One thing we forgot to update each time and needs correcting: here the version is still wrong: https://godot-kotl.in/en/stable/contribution/setup/
> > 
> > 
> > > > Just as a note: remember to move the stable tag so the website get's updated. :-)
> > 
> > 
> > > 
> > 
> > 
> > > IIRC CI updates stable tag when releasing
> > 
> > 
> > Yeah it should but IIRC it does not work reliably. Didn't we have some problems with it in the past? When i look at our current documentation website, it doesn't seem up to date to me? For example see the version here: https://godot-kotl.in/en/stable/user-guide/versioning/
> 
> True, did not catch this. But stable tag is up to date :/

Probably we need to set the stable tag before the actual version tag?

**Comment by piiertho** [comment]
That's what we do already IIRC

**Review by chippmann — DISMISSED** [review]

**Review by CedNaru — APPROVED** [review]

**Review by CedNaru — APPROVED** [review]

**Review by chippmann — APPROVED** [review]

**Review by CedNaru — APPROVED** [review]

**Pull request merged**
