### PR TITLE
Fix max arg size

### PR DESCRIPTION
**Pull request by chippmann**
Fixes:  #491

~~**Note:** Depends on changes from #487 hence the base branch is not `master`. Once #487 is merged, I'll change the base branch (but it should change to master automatically anyways)~~

### CODE REVIEW

**Review by piiertho — APPROVED** [review]

**Comment by chippmann** [comment]
Should we also bump the max allowed arg count of the constructors to 8?

**Comment by piiertho** [comment]
> Should we also bump the max allowed arg count of the constructors to 8?

I think we should

**Review by CedNaru — CHANGES_REQUESTED** [review]
To increase the number of arguments in constructor, we have to:
-  Increase the value of the contraint constant.
-  Add the new generic functions to the list of [KTConstructors](https://github.com/utopia-rise/godot-kotlin-jvm/blob/6540d73e8263f4aab9392243456990fb86016f93/kt/godot-library/src/main/kotlin/godot/core/Constructors.kt#L106)
-  We also have to add the new KTFunctions to the [registration file](https://github.com/utopia-rise/godot-kotlin-jvm/blob/638c3d4767f057389d736384c521105e6d2005a3/kt/godot-library/src/main/kotlin/godot/registration/Registration.kt#L377)

**Review by CedNaru — DISMISSED** [review]
To the moon

**Review by piiertho — APPROVED** [review]

**Review by CedNaru — APPROVED** [review]

**Pull request merged**
