### PR TITLE
Update kotlin to `2.0.20` and update other dependencies

### PR DESCRIPTION
**Pull request by chippmann**
This also prepares the api-gen for a kotlin poet update to the latest version. But because of https://github.com/square/kotlinpoet/issues/1759 the update cannot be performed yet.

### CODE REVIEW

**Review by CedNaru — APPROVED** [review]

**Comment by piiertho** [comment]
Can you solve the TODO in here: https://github.com/utopia-rise/godot-kotlin-jvm/blob/570463439a096287db38cfcce965108938ab57dd/kt/api-generator/src/main/kotlin/godot/codegen/traits/IDocumented.kt#L88 ?

**Review by CedNaru — CHANGES_REQUESTED** [review]
Kotlin 2.0.20 just got released

**Review by CedNaru — APPROVED** [review]

**Comment by piiertho** [comment]
Why tests are failing ?

**Comment by chippmann** [comment]
> Why tests are failing ?

Just because of a slow runner. We ran into the test execution time limit of 30 minutes i set a while ago.
Will rerun it

**Review by piiertho — APPROVED** [review]

**Pull request merged**
