### PR TITLE
feature/use scons cach in ci

### PR DESCRIPTION
**Pull request by piiertho**
This enables scons cache to fasten CI builds. Unfortunately this does not seems to fasten on windows build, maybe someone will have an idea.

### CODE REVIEW

**Review by raniejade — COMMENTED** [review]
How big of an improvement are we talking about? Also, how is the cache cleaned up? Does scons take care of that? If not, the cache may continue to grow and the benefits we get from caching is lost because it will take a while to download the cache.

**Comment by piiertho** [comment]
> How big of an improvement are we talking about? Also, how is the cache cleaned up? Does scons take care of that? If not, the cache may continue to grow and the benefits we get from caching is lost because it will take a while to download the cache.

Cache is per branch.
Files would be overriden if there's any change (we're talking about `.o` / `.obj` files).  
It reduces a lot compilation times if a build has already been done in a PR, as it will use former binairies.

image

**Comment by raniejade** [comment]
> Cache is per branch.

What happens to older cache branches? i.e after being merged.

**Comment by piiertho** [comment]
> > Cache is per branch.
> 
> What happens to older cache branches? i.e after being merged.

From cache action readme:

A repository can have up to 5GB of caches. Once the 5GB limit is reached, older caches will be evicted based on when the cache was last accessed. Caches that are not accessed within the last week will also be evicted.

So it seems to be already managed.

**Review by raniejade — APPROVED** [review]
LGTM - cache is localized to a PR so that's good.

**Review by chippmann — APPROVED** [review]

**Pull request merged**
