### PR TITLE
Add JetBrains GameDev Days 2024 video on the docs' index

### PR DESCRIPTION
**Pull request by gabryon99**
Following your good presentation on the bindings, I thought it may be a good idea to show it to people new to the project. The video is added on the index page of documentation, under a new `Quick Overview` section.

Plus, the JetBrains logo has been updated on the `README.md`

Screenshot 2024-10-11 at 11 43 33

### CODE REVIEW

**Comment by CedNaru** [comment]
Even if timecoded, I would probably wait for Jetbrains to publish the standalone video, which they usually do over time after their events.

**Comment by gabryon99** [comment]
Good point. Hopefully it should not take that long before the standalone video is published.

**Comment by chippmann** [comment]
TBH I'd be fine with the timestamped one until the "real" cut is out. Then we could still update it

**Review by chippmann — APPROVED** [review]

**Comment by chippmann** [comment]
Thx a lot @gabryon99

**Comment by CedNaru** [comment]
The video is up:
https://www.youtube.com/watch?v=Td7JbrGGa8o

**Review by CedNaru — APPROVED** [review]

**Review by piiertho — APPROVED** [review]

**Pull request merged**
